"""
Clinical Risk Analysis Dashboard — AI-powered diabetes and hypertension risk from clinical notes.
Presents pipeline outputs as readable text, tables, charts, and visual indicators (no raw JSON).
Includes report export: PDF and JSON.
"""

import io
import json
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

# Load .env so TESSERACT_CMD and other vars are available (e.g. for document_parser)
import os
from dotenv import load_dotenv
load_dotenv(_PROJECT_ROOT / ".env")
# Disable CrewAI telemetry to avoid "signal only works in main thread" when run under Streamlit
os.environ.setdefault("CREWAI_DISABLE_TELEMETRY", "true")

import pandas as pd
import streamlit as st
from fpdf import FPDF

from src.document_parser import extract_text_from_file, is_supported_file
from src.orchestrator import run_pipeline
from src.trends import build_patient_trends


def _build_report_data(result):
    """Build structured report dict from pipeline outputs (for JSON export and PDF)."""
    extraction = result.get("extraction") or {}
    summary = result.get("summary") or {}
    risk = result.get("risk_analysis") or {}
    viz = (result.get("visualizations") or {}).get("visualizations") or {}
    patient_id = (extraction.get("patient_id") or "").strip() or "Not specified"
    doctor_summary = (summary.get("doctor_summary") or "").strip()
    patient_summary = (summary.get("patient_summary") or "").strip()
    severity = (viz.get("severity_indicator") or {}).get("level") or "Low"
    scores = viz.get("risk_scores") or {}
    hypertension_score = float(scores.get("hypertension_score") or 0)
    diabetes_score = float(scores.get("diabetes_score") or 0)
    evidence = viz.get("evidence_chart") or []
    evidence_rows = []
    if isinstance(evidence, list):
        for item in evidence:
            if isinstance(item, dict):
                evidence_rows.append({
                    "measurement": str(item.get("label") or "").strip() or "—",
                    "value": str(item.get("value") or "").strip() or "—",
                })
    key_flags = summary.get("key_flags") or []
    key_flags = [str(f).strip() for f in key_flags if str(f).strip()]
    data_gaps = summary.get("data_gaps") or []
    data_gaps = [str(g).strip() for g in data_gaps if str(g).strip()]
    return {
        "report_title": "Clinical Risk Analysis Report",
        "generated_by": "AI Clinical Analyzer",
        "patient_id": patient_id,
        "doctor_summary": doctor_summary,
        "patient_summary": patient_summary,
        "risk_severity": severity,
        "hypertension_score": hypertension_score,
        "diabetes_score": diabetes_score,
        "clinical_evidence": evidence_rows,
        "key_flags": key_flags,
        "data_gaps": data_gaps,
    }


def _pdf_safe_text(s):
    """Ensure text fits PDF: replace problematic chars and limit line length for fpdf."""
    if not s or not isinstance(s, str):
        return ""
    s = s.replace("\x00", "").strip()
    return s[:8000] if len(s) > 8000 else s


def _build_pdf_bytes(report):
    """Generate PDF report bytes from structured report data."""
    pdf = FPDF()
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    w = pdf.epw  # effective width (page width minus margins)
    if w <= 0:
        w = 170  # fallback A4 approximate
    pdf.set_font("Helvetica", "B", size=16)
    pdf.multi_cell(w, 10, _pdf_safe_text(report["report_title"]), align="C")
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(f"Generated by {report['generated_by']}"), align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(w, 6, _pdf_safe_text(f"Patient ID: {report['patient_id']}"), ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Doctor Summary", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(report["doctor_summary"] or "No doctor summary available."))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Patient Explanation", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(report["patient_summary"] or "No patient summary available."))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Risk Severity", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(w, 6, f"Level: {report['risk_severity']}", ln=True)
    pdf.cell(w, 6, f"Hypertension Risk Score: {report['hypertension_score']:.2f}", ln=True)
    pdf.cell(w, 6, f"Diabetes Risk Score: {report['diabetes_score']:.2f}", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Clinical Evidence", ln=True)
    pdf.set_font("Helvetica", size=10)
    if report["clinical_evidence"]:
        with pdf.table() as table:
            row = table.row()
            row.cell("Measurement")
            row.cell("Value")
            for r in report["clinical_evidence"]:
                row = table.row()
                row.cell(_pdf_safe_text(r.get("measurement", ""))[:80])
                row.cell(_pdf_safe_text(r.get("value", ""))[:80])
    else:
        pdf.multi_cell(w, 6, "No evidence data available.")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Key Clinical Flags", ln=True)
    pdf.set_font("Helvetica", size=10)
    if report["key_flags"]:
        for f in report["key_flags"]:
            pdf.multi_cell(w, 6, "  - " + _pdf_safe_text(f))
    else:
        pdf.multi_cell(w, 6, "None identified.")
    pdf.ln(2)

    if report["data_gaps"]:
        pdf.set_font("Helvetica", "B", size=11)
        pdf.cell(w, 8, "Data Gaps", ln=True)
        pdf.set_font("Helvetica", size=10)
        for g in report["data_gaps"]:
            pdf.multi_cell(w, 6, "  - " + _pdf_safe_text(g))

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.getvalue()

st.set_page_config(page_title="Clinical Risk Analysis Dashboard", layout="wide")

# ——— Section 1: Title ———
st.title("Clinical Risk Analysis Dashboard")
st.markdown("*AI‑powered analysis of diabetes and hypertension risk from clinical notes.*")
st.divider()

# ——— Section 2: Upload Clinical Report ———
st.subheader("Upload Clinical Report")
st.caption("Provide a patient identifier, then paste clinical text **or** upload a file (PDF, DOCX, PNG, JPG).")
patient_id_input = st.text_input(
    "Patient ID",
    value="",
    placeholder="e.g. MRN1234 or internal patient code",
)
clinical_note = st.text_area(
    "Paste clinical or discharge note",
    height=200,
    placeholder="Paste discharge summary or clinical note text here...",
    label_visibility="collapsed",
)
uploaded_file = st.file_uploader(
    "Or upload a file",
    type=["pdf", "docx", "png", "jpg", "jpeg"],
    label_visibility="collapsed",
)
run_clicked = st.button("Analyze", type="primary", use_container_width=False)

if run_clicked:
    clinical_text = None
    from_file = False
    if uploaded_file is not None:
        if not is_supported_file(uploaded_file.name):
            st.warning("Unsupported file type. Please upload PDF, DOCX, PNG, or JPG.")
        else:
            file_bytes = uploaded_file.read()
            clinical_text, err = extract_text_from_file(file_bytes, uploaded_file.name)
            if err:
                st.warning(err)
            else:
                from_file = True
    if clinical_text is None and not (uploaded_file is not None and not is_supported_file(uploaded_file.name)):
        pasted = (clinical_note or "").strip()
        if pasted:
            clinical_text = pasted
    if clinical_text:
        if from_file:
            st.info("Clinical text extracted successfully. Running analysis...")
        with st.spinner("Running pipeline (Extraction → Risk Analysis → Summary → Visualization)…"):
            try:
                patient_id_effective = (patient_id_input or "").strip() or "unknown"
                input_type = "text"
                if from_file and uploaded_file is not None:
                    input_type = (uploaded_file.name.rsplit(".", 1)[-1] or "file").lower()
                result = run_pipeline(clinical_text, patient_id=patient_id_effective, input_type=input_type)
                st.session_state["last_result"] = result
                st.session_state["last_patient_id"] = patient_id_effective
                # Build longitudinal trends from stored DB data (no re-runs).
                st.session_state["patient_trends"] = build_patient_trends(patient_id_effective)
                st.success("Analysis complete.")
            except Exception as e:
                st.error(f"Pipeline failed: {e}")
                st.exception(e)
                if "last_result" in st.session_state:
                    del st.session_state["last_result"]
    elif not (uploaded_file and not is_supported_file(uploaded_file.name)):
        st.warning("Please enter a clinical note or upload a file before running analysis.")

# ——— Sections 3–10: Only when we have a result (no JSON) ———
if "last_result" not in st.session_state:
    st.info("Paste a clinical note or upload a file (PDF, DOCX, PNG, JPG), then click **Analyze** to see results.")
    st.stop()

result = st.session_state["last_result"]
patient_id_for_trends = st.session_state.get("last_patient_id", "")
patient_trends = st.session_state.get("patient_trends")
summary = result.get("summary") or {}
viz = (result.get("visualizations") or {}).get("visualizations") or {}

# ——— Section 3: Doctor Summary ———
st.subheader("Doctor Summary")
doctor_text = (summary.get("doctor_summary") or "").strip()
if doctor_text:
    st.markdown(doctor_text)
else:
    st.caption("No doctor summary available.")

st.divider()

# ——— Section 4: Patient Summary ———
st.subheader("Patient Summary")
patient_text = (summary.get("patient_summary") or "").strip()
if patient_text:
    st.markdown(patient_text)
else:
    st.caption("No patient summary available.")

st.divider()

# ——— Section 5: Risk Severity Indicator ———
st.subheader("Risk Severity")
severity = viz.get("severity_indicator") or {}
level = (severity.get("level") or "Low").strip()
color = (severity.get("color") or "green").strip().lower()
emoji = {"red": "🔴", "orange": "🟠", "green": "🟢"}.get(color, "🟢")
label = f"{emoji} {level.upper()} RISK"
if color == "red":
    st.error(label)
elif color == "orange":
    st.warning(label)
else:
    st.success(label)

st.divider()

# ——— Section 6: Risk Score Bar Chart ———
st.subheader("Clinical Risk Scores")
scores = viz.get("risk_scores") or {}
d_score = float(scores.get("diabetes_score") or 0)
h_score = float(scores.get("hypertension_score") or 0)
chart_df = pd.DataFrame(
    {"Risk Score": [d_score, h_score]},
    index=["Diabetes", "Hypertension"],
)
st.bar_chart(chart_df)

st.divider()

# ——— Section 7: Clinical Evidence Table ———
st.subheader("Clinical Evidence")
evidence = viz.get("evidence_chart") or []
if isinstance(evidence, list) and evidence:
    rows = []
    for item in evidence:
        if isinstance(item, dict):
            rows.append({
                "Measurement": str(item.get("label") or "").strip() or "—",
                "Value": str(item.get("value") or "").strip() or "—",
            })
    if rows:
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
    else:
        st.caption("No evidence data available.")
else:
    st.caption("No evidence data available.")

st.divider()

# ——— Section 8: Key Clinical Flags ———
st.subheader("Key Clinical Flags")
flags = summary.get("key_flags") or []
if isinstance(flags, list) and flags:
    for f in flags:
        text = str(f).strip()
        if text:
            st.markdown(f"• {text}")
else:
    st.caption("No key flags identified.")

st.divider()

# ——— Section 9: Data Gaps ———
gaps = summary.get("data_gaps") or []
if isinstance(gaps, list) and gaps:
    gap_texts = [str(g).strip() for g in gaps if str(g).strip()]
    if gap_texts:
        st.subheader("Data Gaps")
        with st.container():
            st.warning("The following clinically relevant information was not found in the note:")
            for g in gap_texts:
                st.markdown(f"• {g}")

st.divider()

# ——— Section 10: Patient Trends (Longitudinal History) ———
st.subheader("Patient Trends")
if patient_trends and isinstance(patient_trends, dict):
    t = patient_trends.get("trends") or {}
    dates = t.get("dates") or []
    a1c = t.get("a1c") or []
    glucose = t.get("glucose") or []
    bp_vals = t.get("bp") or []
    diab_risk = t.get("diabetes_risk") or []
    htn_risk = t.get("hypertension_risk") or []

    if dates:
        # Format dates (remove microseconds, keep date + time if present)
        pretty_dates = [str(d).split(".")[0] for d in dates]

        # Helper to add arrows vs previous value
        def with_trend_arrows(values):
            out = []
            prev = None
            for v in values:
                if v is None:
                    out.append("")
                    prev = v
                    continue
                arrow = ""
                if isinstance(prev, (int, float)) and isinstance(v, (int, float)):
                    if v < prev:
                        arrow = " ↓"
                    elif v > prev:
                        arrow = " ↑"
                out.append(f"{v}{arrow}")
                prev = v
            return out

        # Trend table with arrows
        trend_df = pd.DataFrame(
            {
                "Date": pretty_dates,
                "HbA1c": with_trend_arrows(a1c),
                "Glucose": with_trend_arrows(glucose),
                "BP": bp_vals,
                "Diabetes Risk": with_trend_arrows(diab_risk),
                "Hypertension Risk": with_trend_arrows(htn_risk),
            }
        )
        st.markdown("**Report History**")
        st.dataframe(trend_df, use_container_width=True, hide_index=True)

        # Line charts for risk over time
        chart_df = pd.DataFrame(
            {
                "Date": pretty_dates,
                "Diabetes Risk": diab_risk,
                "Hypertension Risk": htn_risk,
            }
        ).set_index("Date")
        st.markdown("**Risk Over Time**")
        st.line_chart(chart_df)

        # Clinical Insights section
        summary_trend = patient_trends.get("trend_summary") or {}
        diab_label = (summary_trend.get("diabetes") or "stable").lower()
        htn_label = (summary_trend.get("hypertension") or "stable").lower()

        def trend_phrase(label: str, condition: str) -> str:
            if label == "improving":
                return f"{condition} Trend: Improving ↓"
            if label == "worsening":
                return f"{condition} Trend: Worsening ↑"
            return f"{condition} Trend: Stable"

        st.markdown("**Clinical Insights**")
        st.markdown(f"- {trend_phrase(diab_label, 'Diabetes')}")
        st.markdown(f"- {trend_phrase(htn_label, 'Hypertension')}")
    else:
        st.caption("No stored history found for this patient yet. Trends will appear after multiple reports are stored.")
else:
    st.caption("Run an analysis with a patient ID to build longitudinal trends.")

st.divider()

# ——— Section 11: Download Report ———
st.subheader("Download Report")
report_data = _build_report_data(result)
col1, col2 = st.columns(2)
with col1:
    pdf_bytes = _build_pdf_bytes(report_data)
    st.download_button(
        label="Download PDF Report",
        data=pdf_bytes,
        file_name="clinical_risk_analysis_report.pdf",
        mime="application/pdf",
    )
with col2:
    json_str = json.dumps(report_data, indent=2)
    st.download_button(
        label="Download JSON Report",
        data=json_str,
        file_name="clinical_risk_analysis_report.json",
        mime="application/json",
    )
