"""
Clinical Risk Analysis Dashboard — AI-powered diabetes and hypertension risk from clinical notes.
Presents pipeline outputs as readable text, tables, charts, and visual indicators (no raw JSON).
Includes report export: PDF and JSON.
"""

import io
import json
import sys
from pathlib import Path

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(_PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(_PROJECT_ROOT))

import pandas as pd
import streamlit as st
from fpdf import FPDF

from src.orchestrator import run_pipeline


def _build_report_data(result):
    """Build structured report dict from pipeline outputs (for JSON export and PDF)."""
    extraction = result.get("extraction") or {}
    summary = result.get("summary") or {}
    risk = result.get("risk_analysis") or {}
    viz = (result.get("visualizations") or {}).get("visualizations") or {}
    patient_id = (extraction.get("patient_id") or "").strip() or "Not specified"
    doctor_summary = (summary.get("doctor_summary") or "").strip()
    patient_summary = (summary.get("patient_summary") or "").strip()
    severity = (viz.get("severity_indicator") or {}).get("level") or "Low"
    scores = viz.get("risk_scores") or {}
    hypertension_score = float(scores.get("hypertension_score") or 0)
    diabetes_score = float(scores.get("diabetes_score") or 0)
    evidence = viz.get("evidence_chart") or []
    evidence_rows = []
    if isinstance(evidence, list):
        for item in evidence:
            if isinstance(item, dict):
                evidence_rows.append({
                    "measurement": str(item.get("label") or "").strip() or "—",
                    "value": str(item.get("value") or "").strip() or "—",
                })
    key_flags = summary.get("key_flags") or []
    key_flags = [str(f).strip() for f in key_flags if str(f).strip()]
    data_gaps = summary.get("data_gaps") or []
    data_gaps = [str(g).strip() for g in data_gaps if str(g).strip()]
    return {
        "report_title": "Clinical Risk Analysis Report",
        "generated_by": "AI Clinical Analyzer",
        "patient_id": patient_id,
        "doctor_summary": doctor_summary,
        "patient_summary": patient_summary,
        "risk_severity": severity,
        "hypertension_score": hypertension_score,
        "diabetes_score": diabetes_score,
        "clinical_evidence": evidence_rows,
        "key_flags": key_flags,
        "data_gaps": data_gaps,
    }


def _pdf_safe_text(s):
    """Ensure text fits PDF: replace problematic chars and limit line length for fpdf."""
    if not s or not isinstance(s, str):
        return ""
    s = s.replace("\x00", "").strip()
    return s[:8000] if len(s) > 8000 else s


def _build_pdf_bytes(report):
    """Generate PDF report bytes from structured report data."""
    pdf = FPDF()
    pdf.set_margins(left=20, top=20, right=20)
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()
    w = pdf.epw  # effective width (page width minus margins)
    if w <= 0:
        w = 170  # fallback A4 approximate
    pdf.set_font("Helvetica", "B", size=16)
    pdf.multi_cell(w, 10, _pdf_safe_text(report["report_title"]), align="C")
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(f"Generated by {report['generated_by']}"), align="C")
    pdf.ln(4)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(w, 6, _pdf_safe_text(f"Patient ID: {report['patient_id']}"), ln=True)
    pdf.ln(4)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Doctor Summary", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(report["doctor_summary"] or "No doctor summary available."))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Patient Explanation", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.multi_cell(w, 6, _pdf_safe_text(report["patient_summary"] or "No patient summary available."))
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Risk Severity", ln=True)
    pdf.set_font("Helvetica", size=10)
    pdf.cell(w, 6, f"Level: {report['risk_severity']}", ln=True)
    pdf.cell(w, 6, f"Hypertension Risk Score: {report['hypertension_score']:.2f}", ln=True)
    pdf.cell(w, 6, f"Diabetes Risk Score: {report['diabetes_score']:.2f}", ln=True)
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Clinical Evidence", ln=True)
    pdf.set_font("Helvetica", size=10)
    if report["clinical_evidence"]:
        with pdf.table() as table:
            row = table.row()
            row.cell("Measurement")
            row.cell("Value")
            for r in report["clinical_evidence"]:
                row = table.row()
                row.cell(_pdf_safe_text(r.get("measurement", ""))[:80])
                row.cell(_pdf_safe_text(r.get("value", ""))[:80])
    else:
        pdf.multi_cell(w, 6, "No evidence data available.")
    pdf.ln(2)

    pdf.set_font("Helvetica", "B", size=11)
    pdf.cell(w, 8, "Key Clinical Flags", ln=True)
    pdf.set_font("Helvetica", size=10)
    if report["key_flags"]:
        for f in report["key_flags"]:
            pdf.multi_cell(w, 6, "  - " + _pdf_safe_text(f))
    else:
        pdf.multi_cell(w, 6, "None identified.")
    pdf.ln(2)

    if report["data_gaps"]:
        pdf.set_font("Helvetica", "B", size=11)
        pdf.cell(w, 8, "Data Gaps", ln=True)
        pdf.set_font("Helvetica", size=10)
        for g in report["data_gaps"]:
            pdf.multi_cell(w, 6, "  - " + _pdf_safe_text(g))

    buf = io.BytesIO()
    pdf.output(buf)
    buf.seek(0)
    return buf.getvalue()

st.set_page_config(page_title="Clinical Risk Analysis Dashboard", layout="wide")

# ——— Section 1: Title ———
st.title("Clinical Risk Analysis Dashboard")
st.markdown("*AI‑powered analysis of diabetes and hypertension risk from clinical notes.*")
st.divider()

# ——— Section 2: Input ———
st.subheader("Input Clinical Note")
clinical_note = st.text_area(
    "Paste clinical or discharge note below",
    height=280,
    placeholder="Paste discharge summary or clinical note text here...",
    label_visibility="collapsed",
)
run_clicked = st.button("Analyze", type="primary", use_container_width=False)

if run_clicked:
    note = (clinical_note or "").strip()
    if not note:
        st.warning("Please enter a clinical note before running analysis.")
    else:
        with st.spinner("Running pipeline (Extraction → Risk Analysis → Summary → Visualization)…"):
            try:
                result = run_pipeline(note)
                st.session_state["last_result"] = result
                st.success("Analysis complete.")
            except Exception as e:
                st.error(f"Pipeline failed: {e}")
                st.exception(e)
                if "last_result" in st.session_state:
                    del st.session_state["last_result"]

# ——— Sections 3–9: Only when we have a result (no JSON) ———
if "last_result" not in st.session_state:
    st.info("Paste a clinical note and click **Analyze** to see results.")
    st.stop()

result = st.session_state["last_result"]
summary = result.get("summary") or {}
viz = (result.get("visualizations") or {}).get("visualizations") or {}

# ——— Section 3: Doctor Summary ———
st.subheader("Doctor Summary")
doctor_text = (summary.get("doctor_summary") or "").strip()
if doctor_text:
    st.markdown(doctor_text)
else:
    st.caption("No doctor summary available.")

st.divider()

# ——— Section 4: Patient Summary ———
st.subheader("Patient Summary")
patient_text = (summary.get("patient_summary") or "").strip()
if patient_text:
    st.markdown(patient_text)
else:
    st.caption("No patient summary available.")

st.divider()

# ——— Section 5: Risk Severity Indicator ———
st.subheader("Risk Severity")
severity = viz.get("severity_indicator") or {}
level = (severity.get("level") or "Low").strip()
color = (severity.get("color") or "green").strip().lower()
emoji = {"red": "🔴", "orange": "🟠", "green": "🟢"}.get(color, "🟢")
label = f"{emoji} {level.upper()} RISK"
if color == "red":
    st.error(label)
elif color == "orange":
    st.warning(label)
else:
    st.success(label)

st.divider()

# ——— Section 6: Risk Score Bar Chart ———
st.subheader("Clinical Risk Scores")
scores = viz.get("risk_scores") or {}
d_score = float(scores.get("diabetes_score") or 0)
h_score = float(scores.get("hypertension_score") or 0)
chart_df = pd.DataFrame(
    {"Risk Score": [d_score, h_score]},
    index=["Diabetes", "Hypertension"],
)
st.bar_chart(chart_df)

st.divider()

# ——— Section 7: Clinical Evidence Table ———
st.subheader("Clinical Evidence")
evidence = viz.get("evidence_chart") or []
if isinstance(evidence, list) and evidence:
    rows = []
    for item in evidence:
        if isinstance(item, dict):
            rows.append({
                "Measurement": str(item.get("label") or "").strip() or "—",
                "Value": str(item.get("value") or "").strip() or "—",
            })
    if rows:
        st.dataframe(pd.DataFrame(rows), use_container_width=True, hide_index=True)
    else:
        st.caption("No evidence data available.")
else:
    st.caption("No evidence data available.")

st.divider()

# ——— Section 8: Key Clinical Flags ———
st.subheader("Key Clinical Flags")
flags = summary.get("key_flags") or []
if isinstance(flags, list) and flags:
    for f in flags:
        text = str(f).strip()
        if text:
            st.markdown(f"• {text}")
else:
    st.caption("No key flags identified.")

st.divider()

# ——— Section 9: Data Gaps ———
gaps = summary.get("data_gaps") or []
if isinstance(gaps, list) and gaps:
    gap_texts = [str(g).strip() for g in gaps if str(g).strip()]
    if gap_texts:
        st.subheader("Data Gaps")
        with st.container():
            st.warning("The following clinically relevant information was not found in the note:")
            for g in gap_texts:
                st.markdown(f"• {g}")

st.divider()

# ——— Section 10: Download Report ———
st.subheader("Download Report")
report_data = _build_report_data(result)
col1, col2 = st.columns(2)
with col1:
    pdf_bytes = _build_pdf_bytes(report_data)
    st.download_button(
        label="Download PDF Report",
        data=pdf_bytes,
        file_name="clinical_risk_analysis_report.pdf",
        mime="application/pdf",
    )
with col2:
    json_str = json.dumps(report_data, indent=2)
    st.download_button(
        label="Download JSON Report",
        data=json_str,
        file_name="clinical_risk_analysis_report.json",
        mime="application/json",
    )
